---
name: Upgrade Deps
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          set-safe-directory: ${{ github.workspace }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - run: git config --global user.email 'pakkunbot'
      - run: git config --global user.name 'blah+pakkun@cliffano.com'
      - run: sudo make deps-extra-apt
      - run: make clean deps deps-upgrade
      - run: make ci
      - run: git commit -am 'Upgrade dependencies to latest versions'
      - uses: ad-m/github-push-action@v1.0.0
        with:
          tags: false
          github_token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
